version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    labels: ["area:packaging", "type:task"]
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: ["area:ci", "type:task"]
    open-pull-requests-limit: 5
